version: '3.3'

services:
  mongo:
    container_name: mongo-db
    image: mongo:5.0.15
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 30s
      interval: 10s
      retries: 10
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
      - MONGO_INITDB_DATABASE=app_db
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=passw0rd
    volumes:
      - ./volume/db-init:/docker-entrypoint-initdb.d/
      - mongo-db:/data/db
    ports:
      - 27017:27017
    logging:
        options:
            max-size: 1g

  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passw0rd
      - ME_CONFIG_MONGODB_URL=mongodb://root:passw0rd@mongo:27017/
    ports:
      - 8081:8081
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
    logging:
        options:
            max-size: 1g

volumes:
  mongo-db: